/*
 * ==========================================================================
 * Copyright (C) 2019-2022 HCL America, Inc. ( http://www.hcl.com/ )
 *                            All rights reserved.
 * ==========================================================================
 * Licensed under the  Apache License, Version 2.0  (the "License").  You may
 * not use this file except in compliance with the License.  You may obtain a
 * copy of the License at <http://www.apache.org/licenses/LICENSE-2.0>.
 *
 * Unless  required  by applicable  law or  agreed  to  in writing,  software
 * distributed under the License is distributed on an  "AS IS" BASIS, WITHOUT
 * WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the  specific language  governing permissions  and limitations
 * under the License.
 * ==========================================================================
 */
package com.hcl.domino.jna.internal.structs;
import java.security.AccessController;
import java.security.PrivilegedAction;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class HtmlApi_UrlArgStruct extends BaseStructure {
	/**
	 * CmdArgID identifier<br>
	 * C type : CmdArgID
	 */
	public int Id;
	
	/**
	 * type of target or arg value (e.g., CAVT_String, CAVT_Int, etc.)<br>
	 * C type : CmdArgValueType
	 */
	public int Type;
	/** C type : Value */
	public ValueUnion val;
	
	public HtmlApi_UrlArgStruct() {
		super();
	}
	
	@Override
	protected List<String> getFieldOrder() {
		return Arrays.asList("Id", "Type", "val"); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
	}
	
	/**
	 * @param Id CmdArgID identifier, C type : CmdArgID<br>
	 * @param Type type of target or arg value (e.g., CAVT_String, CAVT_Int, etc.), C type : CmdArgValueType<br>
	 * @param val C type : Value
	 */
	public HtmlApi_UrlArgStruct(int Id, int Type, ValueUnion val) {
		super();
		this.Id = Id;
		this.Type = Type;
		this.val = val;
	}

	public static HtmlApi_UrlArgStruct newInstance(final int Id, final int Type, final ValueUnion val) {
		return AccessController.doPrivileged((PrivilegedAction<HtmlApi_UrlArgStruct>) () -> new HtmlApi_UrlArgStruct(Id, Type, val));
	}

	
	public HtmlApi_UrlArgStruct(Pointer peer) {
		super(peer);
	}

	public static HtmlApi_UrlArgStruct newInstance(final Pointer peer) {
		return AccessController.doPrivileged((PrivilegedAction<HtmlApi_UrlArgStruct>) () -> new HtmlApi_UrlArgStruct(peer));
	}

	public static class ByReference extends HtmlApi_UrlArgStruct implements Structure.ByReference {
		
	};
	
	public static class ByValue extends HtmlApi_UrlArgStruct implements Structure.ByValue {
		
	};
}
