/*
 * ==========================================================================
 * Copyright (C) 2019-2021 HCL America, Inc. ( http://www.hcl.com/ )
 *                            All rights reserved.
 * ==========================================================================
 * Licensed under the  Apache License, Version 2.0  (the "License").  You may
 * not use this file except in compliance with the License.  You may obtain a
 * copy of the License at <http://www.apache.org/licenses/LICENSE-2.0>.
 *
 * Unless  required  by applicable  law or  agreed  to  in writing,  software
 * distributed under the License is distributed on an  "AS IS" BASIS, WITHOUT
 * WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the  specific language  governing permissions  and limitations
 * under the License.
 * ==========================================================================
 */
package com.hcl.domino.jna.internal.structs;
import java.security.AccessController;
import java.security.PrivilegedAction;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class NotesViewColumnFormat4Struct extends BaseStructure {
	/** VIEW_COLUMN_FORMAT_SIGNATURE4 */
	public short Signature;
	/** C type : NFMT */
	public NotesNFMTStruct NumberFormat;
	/** NPREF_xxx */
	public byte NumSymPref;
	/** NNUMSYM_xxx */
	public byte NumSymFlags;
	public int DecimalSymLength;
	public int MilliSepSymLength;
	public int NegativeSymLength;
	public short MilliGroupSize;
	public int Unused1;
	public int Unused2;
	/** NPREF_xxx */
	public byte CurrencyPref;
	/** NCURFMT_xxx */
	public byte CurrencyType;
	/** NCURFMT_xxx */
	public byte CurrencyFlags;
	public int CurrencySymLength;
	public int ISOCountry;
	public short NumberPreference;
	public byte bUnused;
	public int Unused3;
	public int Unused4;
	public NotesViewColumnFormat4Struct() {
		super();
		setAlignType(Structure.ALIGN_NONE);
	}
	
	public static NotesViewColumnFormat4Struct newInstance() {
		return AccessController.doPrivileged((PrivilegedAction<NotesViewColumnFormat4Struct>) () -> new NotesViewColumnFormat4Struct());
	}

	@Override
	protected List<String> getFieldOrder() {
		return Arrays.asList(
			"Signature", //$NON-NLS-1$
			"NumberFormat", //$NON-NLS-1$
			"NumSymPref", //$NON-NLS-1$
			"NumSymFlags", //$NON-NLS-1$
			"DecimalSymLength", //$NON-NLS-1$
			"MilliSepSymLength", //$NON-NLS-1$
			"NegativeSymLength", //$NON-NLS-1$
			"MilliGroupSize", //$NON-NLS-1$
			"Unused1", //$NON-NLS-1$
			"Unused2", //$NON-NLS-1$
			"CurrencyPref", //$NON-NLS-1$
			"CurrencyType", //$NON-NLS-1$
			"CurrencyFlags", //$NON-NLS-1$
			"CurrencySymLength", //$NON-NLS-1$
			"ISOCountry", //$NON-NLS-1$
			"NumberPreference", //$NON-NLS-1$
			"bUnused", //$NON-NLS-1$
			"Unused3", //$NON-NLS-1$
			"Unused4" //$NON-NLS-1$
		);
	}
	public NotesViewColumnFormat4Struct(Pointer peer) {
		super(peer);
		setAlignType(Structure.ALIGN_NONE);
	}
	
	public static NotesViewColumnFormat4Struct newInstance(final Pointer peer) {
		return AccessController.doPrivileged((PrivilegedAction<NotesViewColumnFormat4Struct>) () -> new NotesViewColumnFormat4Struct(peer));
	}

	public static class ByReference extends NotesViewColumnFormat4Struct implements Structure.ByReference {
		
	};
	public static class ByValue extends NotesViewColumnFormat4Struct implements Structure.ByValue {
		
	};
}
