/*
 * ==========================================================================
 * Copyright (C) 2019-2021 HCL America, Inc. ( http://www.hcl.com/ )
 *                            All rights reserved.
 * ==========================================================================
 * Licensed under the  Apache License, Version 2.0  (the "License").  You may
 * not use this file except in compliance with the License.  You may obtain a
 * copy of the License at <http://www.apache.org/licenses/LICENSE-2.0>.
 *
 * Unless  required  by applicable  law or  agreed  to  in writing,  software
 * distributed under the License is distributed on an  "AS IS" BASIS, WITHOUT
 * WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the  specific language  governing permissions  and limitations
 * under the License.
 * ==========================================================================
 */
package com.hcl.domino.jna.internal.structs;

import java.security.AccessController;
import java.security.PrivilegedAction;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class NotesObjectDescriptorStruct extends BaseStructure {
	/** Type of object (OBJECT_xxx) */
	public short ObjectType;
	/** Object ID of the object in THIS FILE */
	public int RRV;
	
	/**
	 * @deprecated only public to be used by JNA; use static newInstance method instead to run in AccessController.doPrivileged block
	 */
	@Deprecated
	public NotesObjectDescriptorStruct() {
		super();
		setAlignType(Structure.ALIGN_NONE);
	}
	
	public static NotesObjectDescriptorStruct newInstance() {
		return AccessController.doPrivileged((PrivilegedAction<NotesObjectDescriptorStruct>) () -> new NotesObjectDescriptorStruct());
	}
	
	@Override
	protected List<String> getFieldOrder() {
		return Arrays.asList("ObjectType", "RRV"); //$NON-NLS-1$ //$NON-NLS-2$
	}
	
	/**
	 * @param ObjectType Type of object (OBJECT_xxx)<br>
	 * @param RRV Object ID of the object in THIS FILE
	 * @deprecated only public to be used by JNA; use static newInstance method instead to run in AccessController.doPrivileged block
	 */
	@Deprecated
	public NotesObjectDescriptorStruct(short ObjectType, int RRV) {
		super();
		setAlignType(Structure.ALIGN_NONE);
		this.ObjectType = ObjectType;
		this.RRV = RRV;
	}
	
	public static NotesObjectDescriptorStruct newInstance(final short ObjectType, final int RRV) {
		return AccessController.doPrivileged((PrivilegedAction<NotesObjectDescriptorStruct>) () -> new NotesObjectDescriptorStruct(ObjectType, RRV));
	}
	
	/**
	 * @deprecated only public to be used by JNA; use static newInstance method instead to run in AccessController.doPrivileged block
	 * 
	 * @param peer pointer
	 */
	@Deprecated
	public NotesObjectDescriptorStruct(Pointer peer) {
		super(peer);
		setAlignType(Structure.ALIGN_NONE);
	}
	
	public static NotesObjectDescriptorStruct newInstance(final Pointer p) {
		return AccessController.doPrivileged((PrivilegedAction<NotesObjectDescriptorStruct>) () -> new NotesObjectDescriptorStruct(p));
	}
	
	public static class ByReference extends NotesObjectDescriptorStruct implements Structure.ByReference {
		
	};
	public static class ByValue extends NotesObjectDescriptorStruct implements Structure.ByValue {
		
	};
}
