/*
 * ==========================================================================
 * Copyright (C) 2019-2022 HCL America, Inc. ( http://www.hcl.com/ )
 *                            All rights reserved.
 * ==========================================================================
 * Licensed under the  Apache License, Version 2.0  (the "License").  You may
 * not use this file except in compliance with the License.  You may obtain a
 * copy of the License at <http://www.apache.org/licenses/LICENSE-2.0>.
 *
 * Unless  required  by applicable  law or  agreed  to  in writing,  software
 * distributed under the License is distributed on an  "AS IS" BASIS, WITHOUT
 * WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the  specific language  governing permissions  and limitations
 * under the License.
 * ==========================================================================
 */
package com.hcl.domino.jna.internal.structs;
import java.security.AccessController;
import java.security.PrivilegedAction;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class NotesViewColumnFormatStruct extends BaseStructure {
	/** VIEW_COLUMN_FORMAT_SIGNATURE */
	public short Signature;
	/** see VCF1_xxx */
	public short Flags1;
	/** Item name string size */
	public short ItemNameSize;
	/** Title string size */
	public short TitleSize;
	/** Compiled formula size */
	public short FormulaSize;
	/** Constant value size */
	public short ConstantValueSize;
	/**
	 * Display width - 1/8 ave. char <br>
	 * width units
	 */
	public short DisplayWidth;
	/** Display font ID */
	public int FontID;
	/** see VCF2_xxx */
	public short Flags2;
	/**
	 * Number format specification<br>
	 * C type : NFMT
	 */
	public NotesNFMTStruct NumberFormat;
	/**
	 * Time format specification<br>
	 * C type : TFMT
	 */
	public NotesTFMTStruct TimeFormat;
	/** See VIEW_COL_xxx */
	public short FormatDataType;
	/** List Separator */
	public short ListSep;
	public NotesViewColumnFormatStruct() {
		super();
		setAlignType(Structure.ALIGN_NONE);
	}
	
	public static NotesViewColumnFormatStruct newInstance() {
		return AccessController.doPrivileged((PrivilegedAction<NotesViewColumnFormatStruct>) () -> new NotesViewColumnFormatStruct());
	}

	@Override
	protected List<String> getFieldOrder() {
		return Arrays.asList(
			"Signature", //$NON-NLS-1$
			"Flags1", //$NON-NLS-1$
			"ItemNameSize", //$NON-NLS-1$
			"TitleSize", //$NON-NLS-1$
			"FormulaSize", //$NON-NLS-1$
			"ConstantValueSize", //$NON-NLS-1$
			"DisplayWidth", //$NON-NLS-1$
			"FontID", //$NON-NLS-1$
			"Flags2", //$NON-NLS-1$
			"NumberFormat", //$NON-NLS-1$
			"TimeFormat", //$NON-NLS-1$
			"FormatDataType", //$NON-NLS-1$
			"ListSep" //$NON-NLS-1$
		);
	}
	public NotesViewColumnFormatStruct(Pointer peer) {
		super(peer);
		setAlignType(Structure.ALIGN_NONE);
	}
	
	public static NotesViewColumnFormatStruct newInstance(final Pointer peer) {
		return AccessController.doPrivileged((PrivilegedAction<NotesViewColumnFormatStruct>) () -> new NotesViewColumnFormatStruct(peer));
	}

	public static class ByReference extends NotesViewColumnFormatStruct implements Structure.ByReference {
		
	};
	public static class ByValue extends NotesViewColumnFormatStruct implements Structure.ByValue {
		
	};
}
