/*
 * ==========================================================================
 * Copyright (C) 2019-2022 HCL America, Inc. ( http://www.hcl.com/ )
 *                            All rights reserved.
 * ==========================================================================
 * Licensed under the  Apache License, Version 2.0  (the "License").  You may
 * not use this file except in compliance with the License.  You may obtain a
 * copy of the License at <http://www.apache.org/licenses/LICENSE-2.0>.
 *
 * Unless  required  by applicable  law or  agreed  to  in writing,  software
 * distributed under the License is distributed on an  "AS IS" BASIS, WITHOUT
 * WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the  specific language  governing permissions  and limitations
 * under the License.
 * ==========================================================================
 */
package com.hcl.domino.jna.internal.structs;
import java.security.AccessController;
import java.security.PrivilegedAction;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class NotesStringDescStruct extends Structure {
	/** Size of Text */
	public short wSize;
	/**
	 * Pointer to the Text<br>
	 * C type : char*
	 */
	public Pointer pText;
	
	public NotesStringDescStruct() {
		super();
	}

	public static NotesStringDescStruct newInstance() {
		return AccessController.doPrivileged((PrivilegedAction<NotesStringDescStruct>) () -> {
			return new NotesStringDescStruct();
		});
	}

	@SuppressWarnings("nls")
  @Override
  protected List<String> getFieldOrder() {
		return Arrays.asList("wSize", "pText");
	}
	
	/**
	 * @param wSize Size of Text<br>
	 * @param pText Pointer to the Text<br>
	 * C type : char*
	 */
	public NotesStringDescStruct(short wSize, Pointer pText) {
		super();
		this.wSize = wSize;
		this.pText = pText;
	}
	
	public NotesStringDescStruct(Pointer peer) {
		super(peer);
	}
	
	public static NotesStringDescStruct newInstance(Pointer peer) {
		return AccessController.doPrivileged((PrivilegedAction<NotesStringDescStruct>) () -> {
			return new NotesStringDescStruct(peer);
		});
	}

	public static NotesStringDescStruct.ByReference newInstanceByReference() {
		return AccessController.doPrivileged((PrivilegedAction<NotesStringDescStruct.ByReference>) () -> {
			return new NotesStringDescStruct.ByReference();
		});
	}

	public static class ByReference extends NotesStringDescStruct implements Structure.ByReference {
		
	};
	public static class ByValue extends NotesStringDescStruct implements Structure.ByValue {
		
	};
}
