/*
 * ==========================================================================
 * Copyright (C) 2019-2021 HCL America, Inc. ( http://www.hcl.com/ )
 *                            All rights reserved.
 * ==========================================================================
 * Licensed under the  Apache License, Version 2.0  (the "License").  You may
 * not use this file except in compliance with the License.  You may obtain a
 * copy of the License at <http://www.apache.org/licenses/LICENSE-2.0>.
 *
 * Unless  required  by applicable  law or  agreed  to  in writing,  software
 * distributed under the License is distributed on an  "AS IS" BASIS, WITHOUT
 * WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the  specific language  governing permissions  and limitations
 * under the License.
 * ==========================================================================
 */
package com.hcl.domino.jna.internal.structs;
import java.security.AccessController;
import java.security.PrivilegedAction;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class NotesReplicationHistorySummaryStruct extends BaseStructure {
	/**
	 * Time returned from last replication<br>
	 * C type : TIMEDATE
	 */
	public NotesTimeDateStruct ReplicationTime;
	/** Access level at time of replication */
	public short AccessLevel;
	/** Access flags at time of replication */
	public short AccessFlags;
	/** NEVER, SEND, RECEIVE */
	public short Direction;
	/** Server name offset in packed data */
	public int ServerNameOffset;
	/** Server name length in packed data */
	public short ServerNameLength;
	/** File name length in packed data */
	public short FileNameLength;
	/** contains MoreInfo from cache - includes complete replication flag */
	public short MoreInfo;
	/** Room for growth */
	public short wSpare;
	/** Room for growth */
	public int dwSpare;
	
	public NotesReplicationHistorySummaryStruct() {
		super(Structure.ALIGN_DEFAULT);
	}
	
	public static NotesReplicationHistorySummaryStruct newInstance() {
		return AccessController.doPrivileged((PrivilegedAction<NotesReplicationHistorySummaryStruct>) () -> new NotesReplicationHistorySummaryStruct());
	}

	@Override
	protected List<String> getFieldOrder() {
		return Arrays.asList(
			"ReplicationTime", //$NON-NLS-1$
			"AccessLevel", //$NON-NLS-1$
			"AccessFlags", //$NON-NLS-1$
			"Direction", //$NON-NLS-1$
			"ServerNameOffset", //$NON-NLS-1$
			"ServerNameLength", //$NON-NLS-1$
			"FileNameLength", //$NON-NLS-1$
			"MoreInfo", //$NON-NLS-1$
			"wSpare", //$NON-NLS-1$
			"dwSpare" //$NON-NLS-1$
		);
	}
	
	public NotesReplicationHistorySummaryStruct(Pointer peer) {
		super(peer, Structure.ALIGN_DEFAULT);
	}
	
	public static NotesReplicationHistorySummaryStruct newInstance(Pointer peer) {
		return AccessController.doPrivileged((PrivilegedAction<NotesReplicationHistorySummaryStruct>) () -> new NotesReplicationHistorySummaryStruct(peer));
	}
	
	public static class ByReference extends NotesReplicationHistorySummaryStruct implements Structure.ByReference {
		
	};
	public static class ByValue extends NotesReplicationHistorySummaryStruct implements Structure.ByValue {
		
	};
}
