/*
 * ==========================================================================
 * Copyright (C) 2019-2021 HCL America, Inc. ( http://www.hcl.com/ )
 *                            All rights reserved.
 * ==========================================================================
 * Licensed under the  Apache License, Version 2.0  (the "License").  You may
 * not use this file except in compliance with the License.  You may obtain a
 * copy of the License at <http://www.apache.org/licenses/LICENSE-2.0>.
 *
 * Unless  required  by applicable  law or  agreed  to  in writing,  software
 * distributed under the License is distributed on an  "AS IS" BASIS, WITHOUT
 * WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the  specific language  governing permissions  and limitations
 * under the License.
 * ==========================================================================
 */
package com.hcl.domino.jna.internal.structs;
import java.security.AccessController;
import java.security.PrivilegedAction;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class NotesCalendarActionDataStruct extends Structure {
	/** MUST be sizeof(EXT_CALACTION_DATA) - allows for safe expansion of struct in the future */
	public short wLen;
	/**
	 * Required for dwAction: CAL_PROCESS_DELEGATE - disregarded otherwise<br>
	 * C type : char*
	 */
	public Pointer pszDelegateTo;
	/**
	 * Desired new start date/time.  Required for dwAction: CAL_PROCESS_COUNTER - disregarded otherwise<br>
	 * C type : TIMEDATE*
	 */
	public Pointer ptdChangeToStart;
	/**
	 * Desired new end date/time.  Required for dwAction: CAL_PROCESS_COUNTER - disregarded otherwise<br>
	 * C type : TIMEDATE*
	 */
	public Pointer ptdChangeToEnd;
	/**
	 * If populated for CAL_PROCESS_DELEGATE or CAL_PROCESS_DECLINE, used to inform the Chair if<br>
	 * C type : BOOL*
	 */
	public Pointer pfKeepInformed;
	/**
	 * RESERVED - MUST be NULL<br>
	 * C type : void*
	 */
	public Pointer pReserved;
	/**
	 * List of users to add to the specified entry (or entries) as a Required attendee.<br>
	 * C type : LIST*
	 */
	public Pointer pAddNamesReq;
	/**
	 * List of users to add to the specified entry (or entries) as an Optional attendee.<br>
	 * C type : LIST*
	 */
	public Pointer pAddNamesOpt;
	/**
	 * List of users to add to the specified entry (or entries) as an FYI attendee.<br>
	 * C type : LIST*
	 */
	public Pointer pAddNamesFYI;
	/**
	 * List of users to remove from the specified entry (or entries).<br>
	 * C type : LIST*
	 */
	public Pointer pRemoveNames;
	
	/**
	 * @deprecated only public to be used by JNA; use static newInstance method instead to run in AccessController.doPrivileged block
	 */
	@Deprecated
	public NotesCalendarActionDataStruct() {
		super();
//		setAlignType(ALIGN_NONE);
		this.wLen = (short) (size() & 0xffff);
	}
	
	public static NotesCalendarActionDataStruct newInstance() {
		return AccessController.doPrivileged((PrivilegedAction<NotesCalendarActionDataStruct>) () -> new NotesCalendarActionDataStruct());
	}
	
	@Override
	protected List<String> getFieldOrder() {
		return Arrays.asList(
			"wLen", //$NON-NLS-1$
			"pszDelegateTo", //$NON-NLS-1$
			"ptdChangeToStart", //$NON-NLS-1$
			"ptdChangeToEnd", //$NON-NLS-1$
			"pfKeepInformed", //$NON-NLS-1$
			"pReserved", //$NON-NLS-1$
			"pAddNamesReq", //$NON-NLS-1$
			"pAddNamesOpt", //$NON-NLS-1$
			"pAddNamesFYI", //$NON-NLS-1$
			"pRemoveNames" //$NON-NLS-1$
		);
	}
	
	/**
	 * 
	 * @param peer pointer
	 * @deprecated only public to be used by JNA; use static newInstance method instead to run in AccessController.doPrivileged block
	 */
	@Deprecated
	public NotesCalendarActionDataStruct(Pointer peer) {
		super(peer);
//		setAlignType(ALIGN_NONE);
		this.wLen = (short) (size() & 0xffff);
	}
	
	public static NotesCalendarActionDataStruct newInstance(final Pointer peer) {
		return AccessController.doPrivileged((PrivilegedAction<NotesCalendarActionDataStruct>) () -> new NotesCalendarActionDataStruct(peer));
	}
	
	public static class ByReference extends NotesCalendarActionDataStruct implements Structure.ByReference {
		
	};
	public static class ByValue extends NotesCalendarActionDataStruct implements Structure.ByValue {
		public static NotesCalendarActionDataStruct.ByValue newInstance() {
			return AccessController.doPrivileged((PrivilegedAction<ByValue>) () -> new NotesCalendarActionDataStruct.ByValue());
		}
	};
}
