/*
 * ==========================================================================
 * Copyright (C) 2019-2022 HCL America, Inc. ( http://www.hcl.com/ )
 *                            All rights reserved.
 * ==========================================================================
 * Licensed under the  Apache License, Version 2.0  (the "License").  You may
 * not use this file except in compliance with the License.  You may obtain a
 * copy of the License at <http://www.apache.org/licenses/LICENSE-2.0>.
 *
 * Unless  required  by applicable  law or  agreed  to  in writing,  software
 * distributed under the License is distributed on an  "AS IS" BASIS, WITHOUT
 * WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the  specific language  governing permissions  and limitations
 * under the License.
 * ==========================================================================
 */
package com.hcl.domino.jna.internal.structs.security;
import java.util.Arrays;
import java.util.List;

import com.hcl.domino.jna.internal.structs.KFM_PASSWORDStruct;
import com.hcl.domino.misc.NotesConstants;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class KPI_DOWNLOAD_INFO extends Structure {
	/** IDV_authclass_... code */
	public short IDVAuthClass;
	public byte fEnableNBA;
	public byte fDontWriteFileImage;
	public byte fUseInactiveView;
	public byte fUseKfmPW;
	public byte fResync;
	public byte fPWDidntOpenID;
	/** ID file sync not needed */
	public byte fModHashMatches;
	/** Download/resync failed (probably */
	public byte fRetryUsingUpLd;
	/** Set to have lower level code */
	public byte fPh3_Info_Savvy;
	/** OIDC Set to have lower level code */
	public byte fPh3_Info_OIDCSavvy;
	/** Only do the download transaction to check the password */
	public byte fCheckPassword;
	/** C type : char[MAXUSERNAME] */
	public byte[] UserName = new byte[NotesConstants.MAXUSERNAME];
	/** C type : char[MAXPATH] */
	public byte[] IDFileName = new byte[NotesConstants.MAXPATH];
	/** C type : SEC_MEMOBJ_DESC */
	public SEC_MEMOBJ_DESC LoadedFileImage;
	/**
	 * Really an HIDVACTION, which is a ptr<br>
	 * C type : void*
	 */
	public Pointer hIDVCtx;
	/** C type : IDV_PW_SALT */
	public IDV_PW_SALT Salt = new IDV_PW_SALT();
	/** C type : char[MAXUSERPASSWORD] */
	public byte[] RawPassword = new byte[NotesConstants.MAXUSERPASSWORD];
	/**
	 * Used during download resync versions<br>
	 * C type : KFM_PASSWORD*
	 */
	public KFM_PASSWORDStruct pKfmPW = KFM_PASSWORDStruct.newInstance();
	/** C type : IDV_SRV_CONN */
	public IDV_SRV_CONN SrvConn = new IDV_SRV_CONN();
	/** C type : IDV_PH3_OBJECTS */
	public IDV_PH3_OBJECTS PH3 = new IDV_PH3_OBJECTS();
	/**
	 * saml context passed by caller for ID file download<br>
	 * C type : SEC_MEMOBJ_DESC
	 */
	public SEC_MEMOBJ_DESC Ph3CallerContext;
	public KPI_DOWNLOAD_INFO() {
		super();
	}
	@Override
	protected List<String> getFieldOrder() {
		return Arrays.asList(
			"IDVAuthClass", //$NON-NLS-1$
			"fEnableNBA", //$NON-NLS-1$
			"fDontWriteFileImage", //$NON-NLS-1$
			"fUseInactiveView", //$NON-NLS-1$
			"fUseKfmPW", //$NON-NLS-1$
			"fResync", //$NON-NLS-1$
			"fPWDidntOpenID", //$NON-NLS-1$
			"fModHashMatches", //$NON-NLS-1$
			"fRetryUsingUpLd", //$NON-NLS-1$
			"fPh3_Info_Savvy", //$NON-NLS-1$
			"fPh3_Info_OIDCSavvy", //$NON-NLS-1$
			"fCheckPassword", //$NON-NLS-1$
			"UserName", //$NON-NLS-1$
			"IDFileName", //$NON-NLS-1$
			"LoadedFileImage", //$NON-NLS-1$
			"hIDVCtx", //$NON-NLS-1$
			"Salt", //$NON-NLS-1$
			"RawPassword", //$NON-NLS-1$
			"pKfmPW", //$NON-NLS-1$
			"SrvConn", //$NON-NLS-1$
			"PH3", //$NON-NLS-1$
			"Ph3CallerContext" //$NON-NLS-1$
		);
	}
	public KPI_DOWNLOAD_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends KPI_DOWNLOAD_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends KPI_DOWNLOAD_INFO implements Structure.ByValue {
		
	};
}
