on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  house-keeping:
    runs-on: ubuntu-latest
    steps:
      - name: Keep R12 production to 5
        uses: actions/delete-package-versions@v5.0.0
        with: 
          package-name: 'projectkeep-r12'
          package-type: 'container'
          min-versions-to-keep: 5
          token: ${{ secrets.NUKE_TOKEN }}
      - name: Keep R14 production to 5
        uses: actions/delete-package-versions@v5.0.0
        with: 
          package-name: 'projectkeep-r14'
          package-type: 'container'
          min-versions-to-keep: 5
          token: ${{ secrets.NUKE_TOKEN }}
      - name: Keep R14.5 production to 5
        uses: actions/delete-package-versions@v5.0.0
        with: 
          package-name: 'projectkeep-r145'
          package-type: 'container'
          min-versions-to-keep: 5
          token: ${{ secrets.NUKE_TOKEN }}
