on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
    name: Delete Package Versions
    uses: actions/delete-package-versions@v4.1.1
    with: 
      package-name: 'projectkeep-r12'
      package-type: 'container'
      min-versions-to-keep: 10
