on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  nuke-them:
    name: 'Delete all containers from repository without tags'
    uses: Chizkiyahu/delete-untagged-ghcr-action@v2
    with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository_owner: ${{ github.repository_owner }}
        repository: ${{ github.repository }}
        untagged_only: true
        owner_type: org # or user
