on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  house-keeping:
    runs-on: ubuntu-latest
    steps:
      - name: Keeep production to 5
        uses: actions/delete-package-versions@v4.1.1
        with: 
          package-name: 'hcl-tech-software/projectkeep-r12'
          package-type: 'container'
          min-versions-to-keep: 5
