name: Validate on pull request

on:
  workflow_dispatch:
  pull_request:

jobs:
  buildR12:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Build for r12 with Maven
        run: mvn --batch-mode --update-snapshots -PR12 clean verify javadoc:javadoc

  buildR14:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Compile the POM manipulator
        run: |
          cd multi-version-tool
          mvn --batch-mode clean install
          java -jar target/multi-version-tool-jar-with-dependencies.jar ../ R14
          cd ..
          cat pom.xml
      - name: Build for r14 with Maven
        run: mvn --batch-mode --update-snapshots -PR14 clean verify javadoc:javadoc

  buildR145:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Compile the POM manipulator
        run: |
          cd multi-version-tool
          mvn --batch-mode clean install
          java -jar target/multi-version-tool-jar-with-dependencies.jar ../ R145
          cd ..
          cat pom.xml
      - name: Build for r14.5 with Maven
        run: mvn --batch-mode --update-snapshots -PR145 clean verify javadoc:javadoc
