name: Validate on pull request

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-multi-version-tool:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build the POM manipulator
        run: |
          cd multi-version-tool
          mvn --batch-mode clean install
          cd ..
      - name: Save the POM manipulator
        uses: actions/upload-artifact@v4
        with:
          name: multi-version-tool
          path: multi-version-tool/target/multi-version-tool-jar-with-dependencies.jar
          retention-days: 1

  buildJNX:
    runs-on: ubuntu-latest
    needs: build-multi-version-tool
    strategy:
      matrix:
        options:
          - jdk: 17
            domino: R12
          - jdk: 17
            domino: R14
          - jdk: 21
            domino: R145

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Set up Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.options.jdk }}
          distribution: 'adopt'
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: retrieve the POM manipulator
        uses: actions/download-artifact@v4
        with:
          name: multi-version-tool

      - name: Apply the POM manipulator for ${{ matrix.options.domino }}
        run: |
          java -jar ./multi-version-tool-jar-with-dependencies.jar . ${{ matrix.options.domino }} actual samples
          pwd
          cat pom.xml
      - name: Build for ${{ matrix.options.domino }} with Maven
        run: mvn --batch-mode --update-snapshots -P${{ matrix.options.domino }} clean verify javadoc:javadoc
