name: Push-to-main

# Run workflow on commits to the `master` or `main` branch
on:
  push:
    branches:
      - master
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Extract Project version
        id: project
        run: echo ::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

      - name: Install gpg secret key
        id: install-secret-key
        run: |
          cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Release Maven package to Central
        id: publish-to-central
        # Only publish on develop when the version does end on -SNAPSHOT
        if: ${{ !endsWith(steps.project.outputs.version, '-SNAPSHOT') }}
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          mvn --batch-mode -P deploy \
            -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} \
            clean deploy
